services:
    transcribe_server:
        image: transcribe_server:latest
        container_name: transcribe_server
        runtime: nvidia
        volumes:
            - ./utils:/app/utils
            - ./output:/app/output
        deploy:
            resources:
                reservations:
                    devices:
                    - driver: nvidia
                      count: all
                      capabilities: 
                        - gpu
                        - video
                        - compute
        ports:
            - "5000:5000"